### ISSUE TITLE
add css grid to explain the canvas

### ISSUE THREAD

**Issue by gernotstarke** [arc42/canvas.arc42.org-site#20]
Patrick, let's migrate the testgrid to production :-)

your changes look great - I will add some more content, plus links to details-sections.

**Comment by bitsmuggler** [comment]
@gernotstarke I've committed a first draft of the AIC. What do you think of it? I'm not sure about the animation. The anchor links should work now. To make sure I don't violate your grid, I created a custom class for my canvas. We might want to think about using scss. If the grid looks ok, we can think about reusing the classes.

**Comment by bitsmuggler** [comment]
+ My current version is broken on a mobile view. I'll check this in the evening.

**Comment by gernotstarke** [comment]
I love the hover-animation effect - but prefer to keep the order/size of the items close to the original... (yours all have identical dimensions).

I'll give it another try in the afternoon/evening - I'll be off to an INNOQ meeting in Budapest and have some idle time at the airport...

**Comment by gernotstarke** [comment]
* increased the hover size from 1.015 to 1.02...
otherwise, perfect for me.
