### ISSUE TITLE
Enforce landscape mode on mobile

### ISSUE THREAD

**Issue by bitsmuggler** [arc42/canvas.arc42.org-site#24]
@gernotstarke I've implemented (as a suggestion) a forcing of landscape mode on a mobile in the aic. Because at least the Architecture Inception Canvas doesn't look good in portrait mode. Also, I'm afraid it's difficult to make the Canvas readable in portrait mode on mobile. 

What do you think about this enforcement?

Mobile portrait:

![image](https://github.com/arc42/canvas.arc42.org-site/assets/5189501/7254e3e7-8991-4548-bc67-b7957a466d00)

Mobile landscape:

![image](https://github.com/arc42/canvas.arc42.org-site/assets/5189501/10481f8f-1c8b-4b7f-934f-1f5ccb37ef12)

**Comment by gernotstarke** [comment]
this "enforcement" also triggers when my browser window is small (50% screen size on my 16'' MacBook)

<img width="1699" alt="Screenshot 2023-06-16 um 10 59 23" src="https://github.com/arc42/canvas.arc42.org-site/assets/1233990/d5cbda85-2310-414d-8ea3-bab0afd13dc7">


for me, the "standard" grid is good enough - as I think people can horizontally scroll on their mobile.

maybe I'll ask some usability experts... 

for now, I'll leave it out of the ACC for now.
