### ISSUE TITLE
question: license

### ISSUE THREAD

**Issue by gernotstarke** [arc42/canvas.arc42.org-site#3]
Patrick, is the following license ok for you:

 Software Architecture Canvas © 2023 by Gernot Starke, Patrick Roos and arc42 Contributors is licensed under CC BY-SA 4.0

**Comment by gernotstarke** [comment]
<p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://canvas.arc42.org">Software Architecture Canvas</a> by <span property="cc:attributionName">Gernot Starke, Patrick Roos and arc42 Contributors</span> is licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Attribution-ShareAlike 4.0 International<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1"></a></p>

**Comment by bitsmuggler** [comment]
@gernotstarke Yep, that's ok for me. Thanks. 👍
