### ISSUE TITLE
Draw.io template: Text in header fields "System"/ "Created by"/ "Created for"/ "Date"not visible

### ISSUE THREAD

**Issue by CodingJenka** [arc42/canvas.arc42.org-site#32]
**How to reconstruct**: 

- Type a word into the systemfield for example. 
- Used fontcolor: black. Used backgroundcolor: white (both are default set)
- Klick outside the field

**Tested OS**: Windows, MacOs

**Expected behavior**: 
Typed system description is visible. 

**Actual behavior**: 
White field. If you double click in the middle of the field you mark the previous typed word and see: it is there. But it is not "static" visible. 
![284533798-3fc654a4-5090-4831-be68-7b26c57a60fd](https://github.com/arc42/canvas.arc42.org-site/assets/12326591/6f0fbd97-9486-417a-ba85-c0f6e332687f)
![klickOut](https://github.com/arc42/canvas.arc42.org-site/assets/12326591/ca50b98a-b380-48da-baf4-9507d8c31b72)
![highlighted](https://github.com/arc42/canvas.arc42.org-site/assets/12326591/57d11f4b-33ea-43ec-9e46-d8d215b0c454)

**Comment by gernotstarke** [comment]
thanx @CodingJenka for letting us know. We fixed it - problem were wrong color settings in all header fields.

hope you like the canvas, experience reports and examples welcome!!
