### ISSUE TITLE
add canvas contribution by Marc Gorzala (together with link to his website)

### ISSUE THREAD

**Issue by gernotstarke** [arc42/canvas.arc42.org-site#37]
https://project.dancier.net/documentation/arc42/arc42-canvas.html

done: 1. take canvas, export as png and include in /examples
done: 2. add "button" and redirect to his website (see above)

3. eventually extract a few details from his site to new example-explanation page on canvas.

done - in bullet list below images: In every case, we must not forget to explicitly give credits to him and his open-source project contributors.

**Comment by Per-Starke** [comment]
@gernotstarke what exactly is left here to do? Adding an explanation page for this canvas?
