### ISSUE TITLE
add additional download links/buttons

### ISSUE THREAD

**Issue by gernotstarke** [arc42/canvas.arc42.org-site#39]
People have complained that it's difficult to find the downloads,
as these are ONLY available at the bottom of the respective canvases.

Solution:

* create download page (which is NOT linked in main menu), containing all acc and aic downloads
* add download button on homepage (within "what is a canvas" )
* add download button on examples page (maybe even in the gallery)
* add link to download page in page footer

**Comment by Per-Starke** [comment]
@gernotstarke done, give feedback or wishes for changes if anything is not like you imagined, as always :)

**Comment by gernotstarke** [comment]
replace "canvasses" by singular (reads nicer imho), on title of download page AND on buttons
