### ISSUE TITLE
Add samples

### ISSUE THREAD

**Issue by gernotstarke** [arc42/canvas.arc42.org-site#4]
so people can see HOW the canvas(es) might be used

**Comment by bitsmuggler** [comment]
I like the "Architektur Porträts" (e.g. Architektur Porträt 'Hugo' https://www.embarc.de/architektur-portraet-hugo/) of Stefan Zörner very much. 

As inspiration we could do something similar with the canvas.

**Comment by gernotstarke** [comment]
as we have some examples, I close this issue
