### ISSUE TITLE
create version for Miroverse

### ISSUE THREAD

**Issue by gernotstarke** [arc42/canvas.arc42.org-site#7]
Martina ("m") suggested this, she will investigate

**Comment by bitsmuggler** [comment]
@gernotstarke  How do we proceed here?  I suggest that the both canvas come with the same "template style". If you / Martina wanted, I can help here.

**Comment by gernotstarke** [comment]
during the upcoming weeks, I won't invest any time there. Currently sitting next to Martina:

She inquired at Miro, still no answer.

Proposal: 
* start with a regular miro board, one for each of our two canvases
* provide the board-backup (.rtb file) for download
* later, make that board an "official" template

**Comment by bitsmuggler** [comment]
Thanks for your answer. That is fine with me.

**Comment by bitsmuggler** [comment]
Both canvas are now on miroverse:

* Architecture Inception Canvs: https://miro.com/miroverse/architecture-inception-canvas/
* Architecture Communication Canvas: https://miro.com/miroverse/architecture-communication-canvas/
