### ISSUE TITLE
question: Social Icons in Footer

### ISSUE THREAD

**Issue by gernotstarke** [arc42/canvas.arc42.org-site#9]
@bitsmuggler currently the social icons link to my (LinkedIn, YouTube, dev.to) accounts.

I've no good idea how to handle that, as the subdomain is teamwork...

Proposal: 

* delete youtube and dev.to
* let linkedin point to the arc42 group (which is pretty inactive, but that may change)

other ideas?

**Comment by bitsmuggler** [comment]
@gernotstarke  Yes, that is a good suggestion.

IMHO we can link our personal channels on the [contributors](https://canvas.arc42.org/contributors) page. What do you think about this idea?

**Comment by gernotstarke** [comment]
yes - let's put LinkedIn, Twitter & Co on the contributor page.

**Comment by gernotstarke** [comment]
done.
